spring:
  datasource:
    url: jdbc:mysql://localhost:3306/advancedordersystemdb?useSSL=false&serverTimezone=UTC
    username: student
    password: Saurabh@15
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: SELECT 1

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  profiles:
    active: dev

server:
  port: 8080

logging:
  level:
    com.zaxxer.hikari: DEBUG
    org.springframework.jdbc.datasource: DEBUG
